spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barber_db
    username: postgres
    password: root
    hikari:
      schema: barber
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
#    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8189




